# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pysmartcocoon"
version = "0.5.4"

description = "Library built for Home Assistant to integrate with the SmartCocoon"
readme = "README.md"
authors = [{ name = "Dave Pearce", email = "davepearce@live.com" }]
license = { file = "LICENSE" }
requires-python = ">=3.10"

classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]

keywords = ["smartcocoon", "fan"]

dependencies = [
    "aiohttp",
    "async_timeout",
    "paho.mqtt",
    "requests"
]

[project.optional-dependencies]
test = [
    "black==21.9b0",
    "pre-commit==2.15.0",
    "mypy==0.910",
    "pytest==7.2.2",
    "pytest-cov==3.0.0",
]

[project.urls]
Homepage = "https://github.com/davecpearce/pysmartcocoon"

[tool.bumpver]
current_version = "0.5.4"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"'
]

[tool.flake8]
max-line-length = 130
extend-ignore = ["D203", "E203", "E251", "E266", "E302", "E305", "E401", "E402", "E501", "F401", "F403", "W503"]
exclude = [".git", "__pycache__", "dist"]
max-complexity = 10
